//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eden
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int id { get; set; }
        public int SoLuongTonToiThieu { get; set; }
        public Nullable<decimal> MucGiamGia { get; set; }
        public Nullable<int> ThoiGianBaoHanh { get; set; }
    }
}
